Algoritmo "CONTEATE10")

Var
   CONTADOR, valor, salto: INTEIRO


Inicio
      contador <- 0
      escreval ( " Vai contar até quanto??")
      leia(valor)
      escreval ("qual o valor do salto?")
      leia ( salto)
      enquanto (contador <= valor) faca
               escreval (contador)
               contador <- contador + salto
      fimenquanto
      escreval  ("Terminei de contar")



Fimalgoritmo