Algoritmo "treino condicional simples"

Var
   ano, ano_nasc,idade : inteiro


Inicio
      escreva (" em que ano estamos?")
      leia (ano)
      escreva (" em que ano eu nasci?")
      leia (ano_nasc)
      idade <-ano-ano_nasc
      escreval ("Em", ano , " voce terá ", idade)
      se (idade >= 21) entao
         escreval (" E voce já terá atingido a maioridade")
      fimse


Fimalgoritmo

